server:
  port: 8080
spring:
  application:
    name: api-gateway
  messages:
    basename: i18n/messages
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 20000
    jedis:
      pool:
        max-active: 0
        max-wait: -1
        max-idle: 8
        min-idle: 0
zuul:
#  sensitiveHeaders: "*"
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
  shareSecurityContext: true

loginFilter:
  ignoreUris: /user/user/login, /user/user/register