server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: @project.name@
  messages:
    basename: i18n/messages
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/db_neptune_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: scott
    password: liu762327610
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml,mapper/*.xml
  type-aliases-package: com.scott.neptune
  check-config-location: true
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.scott.neptune
  global-config:
    db-column-underline: false
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
  pageSize: 30
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 20000
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  eager-load:
    enabled: true
    clients: user