spring:
  application:
    name: authentication-server
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#      override-none: false
#      fail-fast: true
#      name: ${spring.application.name}
#      profile: ${spring.profiles.active}
eureka:
  instance:
    prefer-ip-address: true
jwt:
  header: Authorization
  headerPrefix: Bearer
  secret: 6AJvUN7UaP0sqkT0
  expiration: 604800