server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://scott:12345678@eureka-server:8761/eureka/
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://serverhost:3306/db_neptune_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: serverhost
    port: 5672
    username: root
    password: 12345678
    virtual-host: /
  sleuth:
    sampler:
      probability: 0
hystrix:
  shareSecurityContext: true
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  eager-load:
    enabled: true
    clients: user
logging:
  level:
    org.springframework.cloud.openfeign: error
    org.springframework.cloud.bus: error
    com.scott.neptune: error